// GENERATED FILE - edit tools/wordgen/build_english_everyday.py instead.
package com.yuan3271.cloudrift.engine.english

/**
 * Tatoeba 英文句子训出来的日常词，共 4,000 个，按出现次数从多到少。
 *
 * 来源：[Tatoeba](https://tatoeba.org) 英文句子导出（`eng_sentences.tsv.bz2`，CC BY 2.0 FR）。
 * 只统计每个词出现了多少次，**句子原文不入库、不随应用分发**；单字母、超过 16 个字母的串
 * 与出现次数少于 4 次的词都不收。
 *
 * 手写表回答的是"课本收过哪些词""手挑了什么词"，这一张回答的是"真人写句子时到底在用哪些词"
 * ——`appointment`、`insurance`、`actually`、`anyway` 这类天天会打、又不是课本词的就是它补的。
 * 放在 [EnglishWords.EVERYDAY] 之后、课标表之前：日常词先补，课本词垫底。
 *
 * 重新生成：`tools/wordgen/fetch_words.sh` 之后跑
 * `python3 tools/wordgen/build_english_everyday.py`。
 */
internal object EnglishEverydayWords {

    val ALL: List<String> = """
        the to that you is in of and he was
        do it for have be me this she his are
        with on my we don't they what not know her
        at didn't said has i'm think like your as can
        did him want will had about all how from there
        go going by were if one time out an up
        told very it's get would here when been but isn't
        who why no doesn't so just us really never need
        should thought good more could got help can't than doing
        tell now them some people their see he's back you're
        much still our only where come wanted i've too or
        take home into any wasn't i'll say something does make
        many day work went won't way today lot always last
        right knew house new made anything that's money over life
        again let asked car off done three before well long
        school love other better please left sure down everything first
        after able am i'd eat find she's look we're knows
        room every things used give years wants saw two might
        put little talk next ever away leave even buy says
        took man himself speak came wouldn't tomorrow old stay already
        these found night needs couldn't because live which there's may
        being must let's started both children book without around what's
        hope feel heard nothing dog aren't most job friends everyone
        world believe probably tried gave yet ask often same happy
        they're stop hard looked those happened door try water its
        enough year own thing read understand soon father best together
        call person yesterday keep through while week each bad name
        looking anymore alone wonder play bought place morning seen late
        someone anyone use wrong called language party lost problem needed
        felt another care great mother few happen food haven't trying
        afraid getting parents kind looks until family pretty idea such
        wait then remember else big talking learn days herself plan
        friend win wish since mind teacher coming having shouldn't hear
        beautiful ready almost he'd likes country working change supposed busy
        decided early open drink phone seems whether you'll married you've
        seem planning lives likely bed also met myself we'll cold
        young living quite tired times police once study waiting sleep
        yourself city face girl eyes important bit truth hasn't show
        meet nice different hand pay become true thinks far small
        gone ago sorry high under woman walk fun wife coffee
        books end turned difficult between hours became longer died seemed
        should've chance bus you'd easy watch start office answer ran
        word meeting makes outside train brother hurt nobody weren't we've
        behind usually themselves against dinner making surprised head whole everybody
        cat question lived god maybe music visit walked write wearing
        hair son matter turn child spent words playing class sick
        table fell boy eating interested tonight finished light drive ate
        part story cannot death angry forget number doctor reason later
        glad kept town park men during kids front hands fire
        taking summer heart free window four actually anybody run five
        reading set lunch company letter close movie began rain street
        afternoon minutes game others trouble helped known broke sister possible
        month enjoy guy full sometimes born tree killed quickly mean
        sat exactly hate brought liked she'd black hot women arrived
        war real inside station goes business students stayed team feeling
        problems trust move stopped they'd bring red works comes fast
        he'll promised several talked large gets questions earth sitting dead
        swim computer moment along picture changed worked scared allowed hospital
        loves loved rather road dress paid ten die thinking watching
        saying rich near cut clothes learning finally white least spend
        favorite safe forgot moved hungry who's store rest caught studying
        dark side age sent accident wrote completely daughter clean thirty
        order thank hit past months interesting kill shoes human listen
        news sun languages sing building mistake half restaurant worried sound
        body weather sit health fish fine walking taken expected wine
        finish wear situation opened six stupid air baby asleep agree
        doubt second it'll future hour strong across evening point careful
        tea sentence less clear lose learned though trip garden hadn't
        showed area break yes given expect river song attention swimming
        played shall strange birthday mine guys speaking floor mom somebody
        homework weekend stand either plans leaving older drunk short poor
        snow fight student milk test catch blue drinking immediately apartment
        deal speaks hotel means girlfriend cry passed box voice miss
        th dogs sense serious won lie worry flowers present closed
        breakfast running kitchen takes neither driving dream husband mad college
        weeks realized suspect bread quiet dangerous cost lying space kiss
        explain admitted pain power united telling crazy government teach sea
        spoke shot crying nor expensive guess couple quit writing video
        states girls certain case sleeping beer written would've ice beach
        dollars willing experience animals trees course decision check whatever sell
        fall public village system dad key upon using bag state
        secret truck thanks paper could've president ones single broken bicycle
        cake information advice blood return hold promise winter upset glass
        cook pick pass watched land staying kid stood agreed noticed
        dance history tennis ought lucky enjoyed fired sentences choice wall
        they'll fix report control standing drove hat nervous opinion invited
        pictures eaten eye send mistakes horse date prefer held visited
        hundred top famous suddenly university countries perfect younger follow cup
        proud prison boss list save group fear smoking middle waited
        missed towards shut happening hurry bank stuff green common asking
        sad worth wash taught alive travel arrested grew seeing huge
        shopping figure support somewhere weight earlier meat native sounds message
        line touch feet mark refused law funny cats peace wind
        among library returned sky threw sold realize tall stole popular
        studied pulled art exam necessary leaves gun received recently noise
        wished they've ride happens prepared fact sign built foreign ground
        heavy woods instead forward relationship speech kissed capital terrible glasses
        moving avoid she'll shirt hoping island forest difference worse desk
        special consider notice deep hardly yours definitely allow injured drank
        convinced smile slept plane ended helping boyfriend hopes extremely project
        whose easily church straight laugh listening umbrella oil keys king
        picked piece economy warm shop mountain price respect rules player
        seat bathroom anywhere gift feels eggs mouth boys minute fishing
        ship science apple slowly airport act followed coat ring offer
        cars natural wedding lied success concert grow where's impossible vacation
        arrive accept ourselves medicine north ball reached birds guitar mosque
        entire gotten piano nature social seriously knife film smell million
        continued smart protect cool empty moon bike locked aware singing
        join movies feelings ahead certainly missing named spring ill planned
        traffic blame wore cause hide bottle gas cooking borrow smoke
        simple admit carry pizza driver absolutely surprise faster managed dropped
        beat giving marry hoped eventually entered offered convince woke within
        confused correct machine energy o'clock seven failed believed cute practice
        football lawyer solve due ideas sleepy perhaps calling bill following
        hates forgotten understood market ordered covered lake handle drinks above
        raining view arm bird cream color laughing teeth share local
        meant beginning eats ticket form none tears carefully wake according
        step main wondered starting considered dictionary spoken disappointed address waste
        fruit chess planet honest fly filled camera sight dressed fresh
        national field chair calm baseball build economic laughed healthy arms
        bear thousand plays type foot excited caused we'd south choose
        reach involved personal except sweet dirty afford international welcome jealous
        bar twice danger weird animal lights escape dating concerned cried
        club translate knowledge normal fit harder continue internet add sex
        buying patient awake card crime hang expecting chocolate boat excuse
        decide wonderful round whenever stars painting low religion taste tent
        stuck games pool fault bored sugar subject legs windows risk
        intend third contact stolen joke marriage throw interest beauty attack
        account leg however begin stories lonely opportunity sports lots lead
        growing conversation eight regret letters keeps answered itself hiding ways
        forgive bridge gonna guilty jail nearly checked fat dreams jobs
        teaching forced discovered dishes talks suggested shower hid murder political
        exist apples tie ivy soup results storm fair impressed service
        explained everywhere uncle obviously gold abroad raised soccer hell easier
        slow lend tough suit responsible manager text pleased clearly complete
        newspaper brothers path purpose grandfather bath radio sort jumped corner
        online lies skin post uses bedroom match required barely camping
        comfortable happiness distance hated flight luck sooner places studies rice
        worst rent television race amazing yourselves disease carried nose lady
        taxi charge unlikely fighting example delicious closer humans listened count
        losing further cross houses silence loud population apologize result changes
        appreciate major novel mess drop force heat jacket permitted gives
        teachers must've dancing boring ocean fixed meaning flat attend meal
        shy spread singer freedom believes dry similar till friendly advised
        saved cheese solution largest bother mood pen plants sandwich society
        imagine rock western denied position pair farm names star behavior
        one's dying smiled mountains handed suggest reality washed neighborhood private
        research holding culture satisfied improve grandmother father's ancient anyway recognize
        garage museum totally evil washing region holiday forever hearing permission
        rude quick soul today's security wet fool century lord roof
        scientists education goal pretended basketball painted innocent brown twenty lay
        songs unable led feed flying modern discuss raise speaker towel
        paint evidence unfortunately remain silent unless available becoming created community
        chicken progress grabbed workers bigger simply strength bright universe lack
        usual vegetables enemy calls appeared accepted although kicked hello upstairs
        center hired level wears salt west paying board apparently climate
        wood unhappy percent rid helps cash successful shit facebook anger
        whom crowd bet plant issue memory truly embarrassed species wallet
        juice member vote lately courage succeed beyond treated basement spot
        thou photo staring wise here's pocket effort apart enter details
        rule prices duty band website button thirteen yellow fairly useful
        thoughts forty enjoying classes blind complicated tickets miles wild math
        handsome don value parked seldom rights size badly brain exhausted
        weak enjoys treat army sheep thousands hung pushed cookies affair
        drugs suitcase punished season breath exercise acting ability amount toilet
        doors excellent nation article media desperate hanging windshield plenty deserve
        headed telephone search joy falling despite determined shocked obvious suppose
        cover soldiers record cleaning cleaned stick flower prove abandoned putting
        fallen rose parking cheap goodbye thy event stomach pressure sang
        curious shows rarely thirsty traveling lazy remained lock camp neighbors
        ears burned create couch lift direction that'll ugly action pleasure
        master appointment tells hall stairs pregnant shape artist disappeared translation
        taller medical horses grass spending members guests absent judge positive
        figured tongue located shared invite solar supermarket attacked favourite military
        suspicious rise committed stone poured chose email character crisis survive
        cops manage alcohol global birth orange owe perfectly belong cancer
        accused reasons kinds suffering data license hole destroyed final golf
        understanding stronger sisters costs biggest schedule experienced program general cookie
        keeping prevent intelligent east added environment guard youtube including issues
        note gate damage pieces constantly theory depressed runs joined condition
        mirror removed finding childhood explanation credit nine lesson warned retired
        jokes express doctors salad belongs politics favor highly map scene
        neck higher desire per fed religious clock journey especially classroom
        refuse process argument terms annoyed based various zoo closet professional
        fingers diet safety midnight parts assume temperature queen cooked acted
        speed illness claims fail rate current stepped matters screaming fuck
        onto finger visiting speakers hill carrying powerful motivated familiar role
        potatoes page property idiot drug faith adopted shoulder recognized source
        rooms cities streets soft toward intended dare daily cards answers
        starts frightened growth laid finds leader wide press horrible climbed
        possibility female okay flew trade development contract pull stared socks
        rushed advantage crossed videos sees confidence actions recommend capable patience
        quality rang complain currently loss cave pants pencil mention draw
        period developed hiking nations professor products greatest changing nearby surface
        remains opposite grateful someday served efforts steal fully downstairs mother's
        failure habit prepare hire confident fan reply skiing cabin task
        court possibly battle people's jump picnic butter world's conditions photos
        spends site hug ashamed theater passport access thick touched entirely
        accent lovely selling sons assumed appear turning mental average signed
        fence career numbers provide gloves divorce fridge properly ends packed
        technology model tastes apologized neighbor areas gay friendship thin department
        deeply focus square borrowed ruined challenge bite suicide castle relax
        degree divorced ear surrounded drew released desert reluctant flag walks
        honey translated complex sharp coach enemies creature uncomfortable union lower
        fill audience justice traveled escaped cousin shoot rare facts brave
        industry introduced placed candy proposal mission trash request prize spirit
        receive clouds threatened noon knowing stage below burning knocked illegal
        yeah skills bottom hurts extra persuade super dear nowhere polite
        emergency hidden fake active suffered fought turns ignored naked trusted
        burst thief salary gym heaven buried arguing backyard wisdom conference
        original fortune engaged ghost youth kilometers riding coronavirus physical claimed
        wishes violence official male aunt presence serve throughout style related
        smells terrified claim anxious toys understands yen total sounded wealth
        mistaken comments poem garbage events cell increase opening remove edge
        sweater unique headache customers struck argue remembered egg chest baked
        smiling effect smarter swear harm nurse kissing officer criminal walls
        factory lent quietly accidentally decisions track graduated boots actor yard
        writer responsibility defend roses depends sand approach engine northern mum
        bench former romantic lips lessons generally stands bags sport parties
        rains minister plate gathered porch grown otherwise fluent talented pet
        complained giraffes election democracy sir owns messages policy ignore climb
        attended millions thee suffer surgery appears reported wealthy pack computers
        spare financial alarm poverty shook magazine motorcycle figs iron teaches
        agreement searched competition product mouse traditional examination apply becomes killing
        organization survived scary recent complaining essential atmosphere sudden blew winning
        treatment asks prime sale policeman mentioned intelligence achieve dust whoever
        announced faces drives tight strict discussed suspected schools options annoying
        training earthquake aggressive tourists equal requires attractive celebrate false magic
        mail pray attic thanked develop captain alien mall foolish waves
        fifty honor humanity goals writes turkey owner construction push laws
        performance expression driver's virus beside cheating tiny families correctly colour
        brings pretend notes reasonable smaller elevator how's hunting ass valuable
        appearance influence directly independence therefore electricity rope shock package giant
        murdered orders border insurance sofa elected autumn players cultural debt
        optimistic repair expert pleasant jam larger weapons introduce man's offended
        opinions stranger yelling daughters succeeded differently bunch concern tied organized
        mobile seek fever homeless switch topic showing describe twelve drawing
        points particular furniture contains re copy strike cinema author difficulty
        double clever gifts hugged beard chosen particularly hijab pie fashion
        object canceled stealing planted goods reads monster term deserves plastic
        goat creative bills eager awful cares literature minds unusual pretending
        colors regularly incident collection series bell steps entrance resources sink
        dessert produce causes burn everyone's van towels nuts content advance
        crowded response partner buildings lit sometime flashlight darkness warning goats
        employees wherever hundreds attitude belt breaking centre nowadays passengers hero
        companies dentist personality permit presents secrets dish fifteen liar central
        couscous document what'll comment researchers constant swore leads published oldest
        insisted groups nap silly director material majority remind approached trail
        shame existence refrigerator airplane tools hi laundry independent pale worker
        pot grandparents occurred preparing rescue ages anytime pity discouraged threat
        guide rough fate aside weed furious legal dreamed demand grab
        slipped didn earn ridiculous degrees stubborn march forth amused negative
        lines ve worn cases gained forces crack channel sunglasses signs
        obey compared potential weapon applied musician rush warn insects begins
        method frustrated pointed miserable dawn scare scientific charged repeat throat
        adult st split heads rode jeans mostly wondering increased greater
        purse shorter tempted papers highest solved pink loudly frequently breathing
        tend fields holidays documents joking helpful metal barking nuclear shown
        sexual generous latest shelf meters blow patients toy attracted retire
        southern electric mathematics passion impress regular indeed deny chances temper
        interview reputation discussion victim massive victory crush politicians grammar image
        exciting pond movement passing coast counter violent seconds sleeps remembers
        identity odd mass heading mystery instructions careless clothing cheated personally
        pride gain attempt arrest mask tail allergic wound reduce assistant
        converted soap princess downtown tax breathe intention laptop cows brush
        direct deaf effects promises stock software firm talent emotional tries
        imagination memories pupils operation slightly crash boxes leading multiple impression
        silver admire novels wasting communicate production grave replace rocks facing
        laughter sells aliens irritated spider fucking diary pure exchange footsteps
        secretary rely scream heavily sides ski leaned improved damaged ordinary
        considering yelled fruits file consequences customer frozen danced significant pounds
        hesitant dumb jack challenges skeptical notebook income snake mansion festival
        lion begun statement branch landed blanket shift beings teenager puppy
        prefers seats kindness meals wooden giraffe code classmates wolf nights
        funeral behave arriving include billion trial prince invented importance destroy
        unknown sake provided manner authority informed cigarette impact medication oven
        detail hurried cruel ruin stress drawer genius snakes grade sword
        poet rejected interests rained grows depression cheaper t-shirt restaurants effective
        graduate fourth divided year's trick begged communication balance experts hobby
        betrayed useless incredible overcome bound watches planets guest shepherd owned
        surely steak learnt might've citizen exists happier invitation separate roll
        severe taxes granted bomb cast forms respond trained crimes shoulders
        screen normally chips rabbit designed exact climbing vain sings horror
        vehicle principal fellow lasted blamed searching tense somewhat link noisy
        replaced screamed blocked basket causing sunny disaster grey potato collect
        gods previous wrapped activity narrow visitors flies sales mayor incredibly
        trapped doesn individual revealed wings roads design relatives makeup poetry
        cow thus crashed temple shelter error kick confessed cafe raw
        closely medlars connection committee basic plain contest activities circumstances weekends
        pandemic holds comfort supper nearest stabbed vocabulary obsessed who'll option
        nonsense fluently loose pressed shore citizens described mixed beating album
        devil contain swam pilot proof row robbed republic affected stays
        balcony ghosts detective password sandwiches bears thrown delivered trains soldier
        limit aid urgent fantastic reliable emotions somehow difficulties limited staff
        conservative lightning islands rising crossing formed saving insane charming violin
        shouted selfish grades block supplies cap experiment experiences deer unfair
        completed doll setting artificial resist advanced pillow knock knees proper
        explore continues battery throwing ease suggestion conflict bush adults farmers
        beans impatient tower measure settled ceremony homes gray knee revenge
        web humor captured dates labor recommended regrets forgiven bowl suitcases
        trans generation golden sensitive puts supply collected tattoo relaxed caf
        acts tour literally risks values fond shaking panic equipment variety
        cancel rainy squirrel ladder envelope posted haunted focused officials authorities
        items gentleman repaired classical suspended sixteen peaceful remote replied vast
        consists shooting unlocked twins wanna wounded disgusting trap achieved resign
        beaten lawn waved commit uniform relatively participate extreme require argued
        junk decades herd stops struggling moves symbol fog shake recovered
        dealing attempted spaghetti backpack wasted wheat loan painful armed jazz
        polish connected struggled poison levels proposed waters worries philosophy bitter
        soil settle good-looking paintings voices protection dedicated opportunities sauce phoned
        explosion dollar vase shadow relieved corn killer texted kidding unexpected
        bottles statue habits base bodies rapidly relations skirt friend's spilled
        defeat volunteer height types subway tire exams hallway services bothering
        pig approaching objects application travelling costume wheel unlucky tasted advise
        behaviour encouraged drowned bees reaction elephant hunger tip waiter rolled
        chairs ladies exit scientist fig sentenced lecture expressed actress persuaded
        youngest guards greatly recorded disagree pollution chased picking chat measures
        arrogant dizzy physics produced sending politician dried gentle investigation bars
        fiction crew dreaming roommate critical cutting bat victims ambulance barn
        treasure dresses spotted lover belly debate lamp stove privacy kingdom
        dancer necklace it'd bone ceiling faced greeted newspapers maintain appropriate
        overweight cop anxiety grandma app sunset systems luggage fuel sunlight
        worrying views charges carries ours cloud moments rumor pork declared
        teacher's shoe temperatures tool someone's expectations swimmer falls guns proved
        reminds recipe poems farmer individuals expects fancy de sore stream
        grand scratch terribly powers unemployed dung earned distant respected wiped
        translating bringing cups children's driven country's accompanied safely decent alright
        racist pages follows defeated collapsed mutual quarter version doubts mud
        attract range fox practicing carpet developing phones awesome spell snowing
        imagined candles agency oranges slammed neighbour damn tooth witness brilliant
        dated avoided celebrated lifted chemical helmet deleted cab puzzled listens
        naturally depend marks voted misses pills jewelry infected sweat pays
        typical bananas cheek characters civil coins precious burnt toast trunk
        sixty ll letting vision wolves troubled accustomed tunnel contribute aim
        struggle rented foods nightmare bitten tear hitting distracted cooperative absence
        strangers investment bucket chain menu honestly length relief sister's stores
        consciousness eve holy tallest beef cared dragged accurate pitch materials
        fled bothered addicted euros robot spiders essay creatures location alphabet
        regretted conscience bleeding tank purple fans inspired rings remarkable unlike
        increasing background pipe slice fascinating loving recover banned gorgeous naive
        blessed carbon budget absolute prevented reminded assistance answering arranged separated
        awkward homesick bones affect cure cage score chemistry dirt sits
        target elderly performed shouting highway jungle sailing biology leaders assured
        excitement rescued unconscious nasty purchased fourteen sector nerves musical circle
        gradually manners mike locker cleared fears established minimum travels lobby
        convert engineer hammer tricks demanded valley supported hearts son's priest
        limits fascinated appreciated curtains wow instantly tore tests discovery shining
        section freezing cigarettes pace environmental fewer seeds attached painter differences
        structure switched spirits minor protected device included ignorance senior envy
        coincidence numerous specific enormous tourist grace neighbours gender strawberry siblings
        stones tone wife's affairs encourage diamond shortly sympathetic ringing territory
        users wave olive cellphone hyena practical standard destiny dozen palace
        creating flu serving pockets allows borders ambitious log choices eleven
        banana liberty stamps besides cherry happily ships cheer cakes trousers
        strawberries concept tap suitable sharing visible intense mix luckily spite
        sincere tiger google toxic offers approve entering babies era delighted
        peanuts prayed examined louder hurting extraordinary shade diseases revolution cultures
        eastern relationships primary sets skating poker buys rural benefit blowing
        closest tested passes route gently abuse zero directions diplomatic oxygen
        tomatoes addition creepy warmer brother's vegetarian campus bitch mysterious coin
        benefits glanced destination exposed bent dog's monkey occupied accomplish chief
        fortunate agent closing troops origin accomplished empire employee checking errors
        nail convenient discussing shops injuries figures fixing cloth promotion accidents
        adventure injury centuries orbit agriculture ending features doctor's pop punishment
        compare prayer suits identify mile spicy forehead historical drivers candle
        cousins academic angel noises elephants skill foundation dislike smoked alike
        helicopter pm shed mushrooms launched curiosity decorated railway pets brushed
        management symptoms snoring knocking strategy insult surprising flood cattle breaks
        discount records rage owes title talkative originally convicted defense criticism
        textbook tape dining devoted telescope jumping disturbed liquid stable vulnerable
        nodded grocery crops harmful breeze branches maid roots drawn dragon
        texting butterfly everything's nails intentions federal rumors competitive seeking wins
        wars junior carrots skinny countryside includes scolded jogging basis wanting
        confirmed tradition forbidden leather clinic praying coward conduct harvest estate
        returning fifth observed command packing what're films corruption chasing volleyball
        longest democratic infrastructure mercury why's solid excused robbery tune hike
        sweets foreigners ankle embarrassing pepper merely kidnapped supportive impressive secretly
        articles root examples mice e-mail visa ideal moral hers pigs
        elsewhere therapy stunned translations concentrate strongly burden hats grapes twin
        raising forests horizon reports principles sheet pushing onions arrives lions
        random bark elections cries ewe heathers arrival comic improving industrial
        observe cheeks carpenter scarf weighs translator flow punched fooled discover
        counting occur cells status winds drama earth's kitten cafeteria afterwards
        pasta fairy shalt visits delayed permanent spelling delivery civilization ties
        presented abandon deadly gather attacks belief necessarily stopping backed bug
        colleagues ignoring deeper sin teenagers folded therapist wounds perform rivers
        keyboard counted palm lab logical sources remarks handwriting superior demands
        balls hopefully meetings anniversary register situations everyday rifle flour officers
        qualified regions overwhelmed opposed apology spy brand beneath harsh virtue
        dug businesses rotten projects contacted loaded passionate phrase sum shirts
        scale flames platform gang sunshine residents interrupted weigh artists alternative
        banks instant nobody's images company's jar bare cameras thrilled incorrect
        baking scratched appetite dumped regard deliver founded scheduled lifestyle overnight
        hesitate pulling identified froze fork chickens stew concerns disappear fried
        opera brains requested element shine charity smooth suffers brief admired
        mere bicycles machines haircut tasty slapped successfully campaign widely hunt
        parrot affection champagne chef freaked eighteen scandal educated reservation marine
        compromise warming pronounce frog thoroughly prohibited complaints honesty awfully parliament
        clearing isolated wool something's messed well-known lemon conclusion exception resigned
        pronunciation cancelled witch stressed zone function earns valid practices bushes
    """.trimIndent()
        .split(Regex("\\s+"))
        .filter { it.isNotBlank() }
}
